apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v8eo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0021-tenant/tkrw-pr714-0075-0021-app/devfile-sample-v8eo@sha256:ee0c846adbbf0bbd5d9bce4fe015f3516d8e556b90f8699ed847a99e9a8a9e0a
        name: my-nodejs
        resources: {}
status: {}
